[versions]

accompanist = "0.37.3"
activity-compose = "1.12.4"
agp = "9.0.1"
coil-compose = "2.7.0"
compose-bom = "2026.02.00"
core-ktx = "1.17.0"
core-splashscreen = "1.2.0"
coroutines = "1.10.2"
credentials = "1.5.0"
datastore-preferences = "1.2.0"
datetime = "0.7.1"
espressoCore = "3.7.0"
firebase-bom = "34.9.0"
generativeai = "0.9.0"
glance = "1.1.1"
gms-google-services = "4.4.4"
googleid = "1.2.0"
gson = "2.13.2"
hilt = "1.3.0"
hilt-android = "2.59.1"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin = "2.3.10"
ksp = "2.3.2"
lifecycle = "2.10.0"
lottie-compose = "6.7.1"
navigation-compose = "2.9.7"
okhttp3 = "5.3.2"
paging = "3.4.1"
play-services-auth = "21.5.0"
relay = "0.3.12"
retrofit = "3.0.0"
room = "2.8.4"
rxandroid = "3.0.2"
rxjava = "3.1.12"
rxkotlin = "3.0.1"
secrets-gradle-plugin = "2.0.1"
serialization-json = "1.10.0"
testng = "7.12.0"
work = "2.11.1"

[libraries]

# androidx.activity
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

# androidx.compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

# androidx.compose.foundation
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

# androidx.compose.material
androidx-compose-material = { group = "androidx.compose.material", name = "material" }

# androidx.compose.material3
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }

# androidx.compose.material3.adaptive
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation" }

# androidx.compose.ui
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# androidx.core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

# androidx.credentials
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }

# androidx.datastore
androidx-datastore-preferences-android = { group = "androidx.datastore", name = "datastore-preferences-android", version.ref = "datastore-preferences" }

# androidx.glance
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }

# androidx.hilt
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }

# androidx.lifecycle
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# androidx.navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

# androidx.paging
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
androidx-paging-rxjava3 = { group = "androidx.paging", name = "paging-rxjava3", version.ref = "paging" }

# androidx.room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }

# androidx.test.espresso
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# androidx.test.ext
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }

# androidx.work
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# com.airbnb.android
com-airbnb-android-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }

# com.google.accompanist
com-google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# com.google.ai.client.generativeai
com-google-ai-client-generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }

# com.google.android.gms
com-google-android-gms-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }

# com.google.android.libraries.identity.googleid
com-google-android-libraries-identity-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

# com.google.android.libraries.mapsplatform.secrets-gradle-plugin
com-google-android-libraries-mapsplatform-secrets-gradle-plugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }

# com.google.code.gson
com-google-code-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# com.google.dagger
com-google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
com-google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android" }

# com.google.devtools.ksp
com-google-devtools-ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
com-google-devtools-ksp-symbol-processing-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# com.google.firebase
com-google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
com-google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
com-google-firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
com-google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
com-google-firebase-database = { group = "com.google.firebase", name = "firebase-database" }

# com.squareup.okhttp3
com-squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
com-squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }

# com.google.relay
com-google-relay-gradle-plugin = { group = "com.google.relay", name = "relay-gradle-plugin", version.ref = "relay" }

# com.squareup.retrofit2
com-squareup-retrofit2-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
com-squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
com-squareup-retrofit2-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
com-squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

# io.coil-kt
io-coilkt-coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }

# io.reactivex.rxjava3
io-reactivex-rxjava3-rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
io-reactivex-rxjava3-rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
io-reactivex-rxjava3-rxkotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rxkotlin" }

# junit
junit = { group = "junit", name = "junit", version.ref = "junit" }

# org.jetbrains.kotlin
org-jetbrains-kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }

# org.jetbrains.kotlinx
org-jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
org-jetbrains-kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
org-jetbrains-kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime"}
org-jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }

# org.testng
org-testng = { group = "org.testng", name = "testng", version.ref = "testng" }

[plugins]

# com.android
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }

# com.google
com-google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "gms-google-services" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-relay = { id = "com.google.relay", version.ref = "relay" }

# org.jetbrains.kotlin
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }